### PR TITLE
Make bot compile and add dockerfile

### PR DESCRIPTION
**Pull request by freaktechnik**
In order to use the bot I needed it to be packaged in a docker container, so I created a dockerfile. I've also fixed it not compiling, presumably due to some tiny silly library update. If you don't want the Dockerfile in this repo that's fine. I'll happily open a PR just with the compile fix.

I think the usage example is also no longer accurate, I needed to do `auto-invite-matrix-bot --config=/path/to/config.yml`.

### CODE REVIEW

**Comment by MTRNord** [comment]
Hi thanks for making the PR. The usage example says the same as you have there. It might be `yml` vs `yaml`. The longer version is used as the default while tbh the shorter version is more common.

**Comment by freaktechnik** [comment]
No, the usage sample crucially shows `--config /path/to/config.yml` without the `=` which leads to the args parsing failing rather cryptically.

**Comment by MTRNord** [comment]
Hm what example are you referring to? The readme only contains this line about it: `Run it with auto-invite-matrix-bot with an addition --config argument to point to your config file` do you mean the `--help` one? Thats from the clap dependency. Might be a bug on their side or a compatibility issue with the terminal you are using

**Comment by freaktechnik** [comment]
Probably the --help one - I assume that's what they output if the parsing of arguments fails. I found out via tgeir docs that they expect the = for long form. I guess that's a bug in the lib then, indeed.

**Pull request merged**
